"""First

Revision ID: f1494e591889
Revises: 054ad6e6d7b6
Create Date: 2024-09-30 14:51:22.316040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1494e591889'
down_revision: Union[str, None] = '054ad6e6d7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'stockId',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tasks', 'stocks', ['stockId'], ['stockId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'stockId',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
